= The Reactive SQL Client, FOLIO fork

This is the FOLIO fork of https://github.com/eclipse-vertx/vertx-sql-client
with this patch being applied to 4.0.*:

* https://github.com/eclipse-vertx/vertx-sql-client/pull/737 "Unsigned long HexSequence for name of PgPreparedStatement"

== Example how to release the FOLIO fork version

Switch to Java 8 if you currently use Java 11.

This example shows how to release 4.0.3-FOLIO.

It is based on the upstream release 4.0.3.

Go to upstream master and Search for the upstream -SNAPSHOT commit immediately after that release.

We need a -SNAPSHOT to run our "mvn release", otherwise "mvn release" will fail.

We find the upstream commit "Releasing 4.0.4-SNAPSHOT" = e26f72f48e116ac1a7468eed2047f0719eb26a46 on Feb 5, 2021.

Go to folio-org/master branch.

We cannot merge commits from other branches into master because commits from Vert.x developers
are rejected as they haven't signed the FOLIO Contributor License Agreement (CLA).

Execute

`git merge e26f72f48e116ac1a7468eed2047f0719eb26a46`

`vim pom.xml`   # change stack.version to 4.0.3

Attention! The next command will automatically push the current branch to GitHub folio-org/vertx-sql-client!

`mvn -DautoVersionSubmodules=true release:clean release:prepare`

Use these versions:

What is the release version for "Vertx SQL Client parent, FOLIO fork"? (io.vertx:vertx-sql-client-parent) 4.0.4: :

4.0.3-FOLIO

What is SCM release tag or label for "Vertx SQL Client parent, FOLIO fork"? (io.vertx:vertx-sql-client-parent) vertx-sql-client-parent-4.0.3-FOLIO: :

v4.0.3-FOLIO

What is the new development version for "Vertx SQL Client parent, FOLIO fork"? (io.vertx:vertx-sql-client-parent) 4.0.4-FOLIO-SNAPSHOT: :

4.0.4-SNAPSHOT

We use the current upstream version as our new development version to avoid any merge conflict when we merge upstream master next time.

